/**
 * Shared Zod schemas for type-safe validation across the application
 * These schemas can be shared with the backend for end-to-end type safety
 */

import { z } from 'zod';

// ============================================================================
// Base Schemas
// ============================================================================

export const mongoIdSchema = z.string().regex(/^[a-fA-F0-9]{24}$/, 'Invalid MongoDB ObjectId');

export const timestampsSchema = z.object({
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});

// ============================================================================
// Session Schemas
// ============================================================================

/**
 * Session Status Enum - Tracks the lifecycle state of a session
 * 
 * Status Flow:
 * SCHEDULED -> OPEN (manual or auto-open) -> ENDED (auto after endTime) or CLOSED (manual)
 */
export const sessionStatusEnumSchema = z.enum([
  'scheduled',
  'open',
  'ended',
  'closed',
  'cancelled',
]);

export type SessionStatusEnum = z.infer<typeof sessionStatusEnumSchema>;

// Keep backward compatibility - isOpen boolean
export const sessionStatusSchema = z.boolean();

export const sessionSchema = z.object({
  _id: mongoIdSchema,
  name: z.string().min(1, 'Session name is required').max(200),
  description: z.string().max(1000).optional(),
  startTime: z.string().datetime(),
  endTime: z.string().datetime(),
  location: z.string().max(200).optional(),
  isOpen: sessionStatusSchema,
  status: sessionStatusEnumSchema.optional().default('scheduled'),
  capacity: z.number().int().nonnegative().optional(),
  checkInsCount: z.number().int().nonnegative().optional(),
  capacityEnforced: z.boolean().optional().default(true),
  requiresRegistration: z.boolean().optional().default(false),
  day: z.number().int().min(1).max(10).optional().default(1),
}).merge(timestampsSchema);

export const createSessionSchema = z.object({
  name: z.string().min(1, 'Session name is required').max(200),
  description: z.string().max(1000).optional(),
  startTime: z.string().min(1, 'Start time is required'),
  endTime: z.string().min(1, 'End time is required'),
  location: z.string().max(200).optional(),
  isOpen: sessionStatusSchema.default(false),
  capacity: z.number().int().nonnegative().optional(),
  capacityEnforced: z.boolean().optional().default(true),
  requiresRegistration: z.boolean().optional().default(false),
  day: z.number().int().min(1).max(10).optional().default(1),
}).refine(
  (data) => new Date(data.endTime) > new Date(data.startTime),
  { message: 'End time must be after start time', path: ['endTime'] }
);

export const updateSessionSchema = z.object({
  name: z.string().min(1).max(200).optional(),
  description: z.string().max(1000).optional(),
  startTime: z.string().optional(),
  endTime: z.string().optional(),
  location: z.string().max(200).optional(),
  isOpen: sessionStatusSchema.optional(),
  capacity: z.number().int().nonnegative().optional(),
  capacityEnforced: z.boolean().optional(),
  requiresRegistration: z.boolean().optional(),
  day: z.number().int().min(1).max(10).optional(),
});

export type Session = z.infer<typeof sessionSchema>;
export type CreateSessionDto = z.input<typeof createSessionSchema>;
export type UpdateSessionDto = z.infer<typeof updateSessionSchema>;

// ============================================================================
// Participant Schemas
// ============================================================================

export const participantStatusSchema = z.enum(['regular', 'ambassador', 'travel_grant']);
export const travelGrantStatusSchema = z.enum(['pending', 'approved', 'rejected']);

export const participantSchema = z.object({
  _id: mongoIdSchema,
  name: z.string().min(1, 'Name is required').max(200),
  email: z.string().email('Invalid email address'),
  organization: z.string().max(200).optional(),
  qrCode: z.string().min(1),
  isActive: z.boolean(),
  status: participantStatusSchema,
  ambassadorPoints: z.number().int().nonnegative(),
  referredParticipantIds: z.array(mongoIdSchema),
  travelGrantApplied: z.boolean(),
  travelGrantApproved: z.boolean().nullable().optional(),
  travelGrantStatus: travelGrantStatusSchema.optional(),
  travelGrantAppliedAt: z.string().datetime().optional(),
  checkInCount: z.number().int().nonnegative().optional(),
}).merge(timestampsSchema);

export const createParticipantSchema = z.object({
  name: z.string().min(1, 'Name is required').max(200),
  email: z.string().email('Invalid email address'),
  organization: z.string().max(200).optional(),
  qrCode: z.string().optional(), // Auto-generated by backend if not provided
  status: participantStatusSchema.default('regular'),
});

export const updateParticipantSchema = z.object({
  name: z.string().min(1).max(200).optional(),
  email: z.string().email().optional(),
  organization: z.string().max(200).optional(),
  isActive: z.boolean().optional(),
  status: participantStatusSchema.optional(),
  ambassadorPoints: z.number().int().nonnegative().optional(),
  travelGrantApplied: z.boolean().optional(),
  travelGrantApproved: z.boolean().optional(),
});

export const bulkParticipantSchema = z.object({
  name: z.string().min(1),
  email: z.string().email(),
  organization: z.string().optional(),
});

export type Participant = z.infer<typeof participantSchema>;
export type CreateParticipantDto = z.infer<typeof createParticipantSchema>;
export type UpdateParticipantDto = z.infer<typeof updateParticipantSchema>;
export type BulkParticipantDto = z.infer<typeof bulkParticipantSchema>;

// ============================================================================
// Check-in Schemas
// ============================================================================

export const checkInStatusSchema = z.enum(['present', 'late', 'absent']);
export const checkInMethodSchema = z.enum(['qr', 'manual']);

export const checkInSchema = z.object({
  _id: mongoIdSchema,
  participantId: z.union([mongoIdSchema, participantSchema]),
  sessionId: z.union([mongoIdSchema, sessionSchema]),
  checkInTime: z.string().datetime(),
  method: checkInMethodSchema.optional(),
  checkedInBy: z.string().optional(),
  notes: z.string().optional(),
  isLate: z.boolean().default(false),
}).merge(timestampsSchema);

export const checkInQrSchema = z.object({
  qrCode: z.string().min(1, 'QR code is required'),
  sessionId: mongoIdSchema,
});

export const checkInManualSchema = z.object({
  participantId: mongoIdSchema,
  sessionId: mongoIdSchema,
});

export type CheckIn = z.infer<typeof checkInSchema>;
export type CheckInQrDto = z.infer<typeof checkInQrSchema>;
export type CheckInManualDto = z.infer<typeof checkInManualSchema>;

// ============================================================================
// Registration Schemas
// ============================================================================

export const registrationStatusSchema = z.enum(['confirmed', 'pending', 'cancelled']);

export const registrationSchema = z.object({
  _id: mongoIdSchema,
  participantId: z.union([mongoIdSchema, participantSchema]),
  sessionId: z.union([mongoIdSchema, sessionSchema]),
  registrationDate: z.string().datetime(),
  status: registrationStatusSchema,
}).merge(timestampsSchema);

export const createRegistrationSchema = z.object({
  participantId: mongoIdSchema,
  sessionId: mongoIdSchema,
  status: registrationStatusSchema.default('confirmed'),
});

export type Registration = z.infer<typeof registrationSchema>;
export type CreateRegistrationDto = z.infer<typeof createRegistrationSchema>;

// ============================================================================
// Participant Details Schema
// ============================================================================

export const participantScoresSchema = z.object({
  type: z.enum(['ambassador', 'travel_grant']),
  points: z.number().optional(),
  referralCount: z.number().optional(),
  applied: z.boolean().optional(),
  approved: z.boolean().optional(),
  applicationDate: z.string().optional(),
  approvalDate: z.string().optional(),
}).nullable();

export const referredParticipantSchema = z.object({
  _id: mongoIdSchema,
  name: z.string(),
  email: z.string().email(),
  organization: z.string().optional(),
  status: z.string(),
});

export const participantDetailsSchema = z.object({
  participant: participantSchema,
  scores: participantScoresSchema,
  referredParticipants: z.array(referredParticipantSchema),
  registrations: z.array(registrationSchema),
  checkIns: z.array(checkInSchema),
});

export type ParticipantScores = z.infer<typeof participantScoresSchema>;
export type ReferredParticipant = z.infer<typeof referredParticipantSchema>;
export type ParticipantDetails = z.infer<typeof participantDetailsSchema>;

// ============================================================================
// API Response Schemas
// ============================================================================

export const apiResponseSchema = <T extends z.ZodTypeAny>(dataSchema: T) =>
  z.object({
    status: z.string(),
    data: dataSchema,
    message: z.string().optional(),
  });

export const apiErrorSchema = z.object({
  status: z.literal('error'),
  message: z.string(),
  errors: z.array(z.object({
    field: z.string().optional(),
    message: z.string(),
  })).optional(),
});

export type ApiResponse<T> = {
  status: string;
  data: T;
  message?: string;
};

export type ApiError = z.infer<typeof apiErrorSchema>;

// ============================================================================
// Pagination Schemas
// ============================================================================

export const paginationParamsSchema = z.object({
  page: z.number().int().positive().default(1),
  limit: z.number().int().positive().max(100).default(20),
  sortBy: z.string().optional(),
  sortOrder: z.enum(['asc', 'desc']).default('desc'),
});

export const paginatedResponseSchema = <T extends z.ZodTypeAny>(itemSchema: T) =>
  z.object({
    items: z.array(itemSchema),
    pagination: z.object({
      page: z.number(),
      limit: z.number(),
      total: z.number(),
      totalPages: z.number(),
      hasMore: z.boolean(),
    }),
  });

export type PaginationParams = z.infer<typeof paginationParamsSchema>;

export type PaginatedResponse<T> = {
  items: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
    hasMore: boolean;
  };
};

// ============================================================================
// Filter Schemas
// ============================================================================

export const participantFiltersSchema = z.object({
  search: z.string().optional(),
  status: participantStatusSchema.optional(),
  isActive: z.boolean().optional(),
  organization: z.string().optional(),
});

export const checkInFiltersSchema = z.object({
  sessionId: mongoIdSchema.optional(),
  participantId: mongoIdSchema.optional(),
  isLate: z.boolean().optional(),
  dateFrom: z.string().datetime().optional(),
  dateTo: z.string().datetime().optional(),
});

export type ParticipantFilters = z.infer<typeof participantFiltersSchema>;
export type CheckInFilters = z.infer<typeof checkInFiltersSchema>;

// ============================================================================
// Admin Dashboard Schemas (Ambassadors & Travel Grants)
// ============================================================================

export const ambassadorLeaderboardItemSchema = z.object({
  _id: mongoIdSchema,
  name: z.string(),
  email: z.string().email(),
  organization: z.string().optional(),
  ambassadorPoints: z.number().int().nonnegative(),
  referredParticipantIds: z.array(mongoIdSchema),
  rank: z.number().int().positive().optional(),
});

export const ambassadorActivitySchema = z.object({
  participant: participantSchema,
  referredParticipants: z.array(
    z.object({
      _id: mongoIdSchema,
      name: z.string(),
      email: z.string().email(),
      organization: z.string().optional(),
      status: z.string(),
      createdAt: z.string().datetime(),
    })
  ),
  totalPoints: z.number().int().nonnegative(),
});

export const travelGrantApplicationSchema = z.object({
  _id: mongoIdSchema,
  name: z.string(),
  email: z.string().email(),
  organization: z.string().optional(),
  travelGrantApplied: z.boolean(),
  travelGrantApproved: z.boolean().nullable(),
  travelGrantAppliedAt: z.string().datetime().optional(),
  travelGrantDecidedAt: z.string().datetime().optional(),
  status: z.string(),
  createdAt: z.string().datetime(),
});

export const travelGrantStatsSchema = z.object({
  total: z.number().int().nonnegative(),
  pending: z.number().int().nonnegative(),
  approved: z.number().int().nonnegative(),
  rejected: z.number().int().nonnegative(),
});

export const travelGrantQualificationSchema = z.object({
  qualified: z.boolean(),
  reason: z.string().optional(),
});

export const participantStatsSchema = z.object({
  total: z.number().int().nonnegative(),
  active: z.number().int().nonnegative(),
  ambassadors: z.number().int().nonnegative(),
  travelGrant: z.number().int().nonnegative(),
});

export const travelGrantApplicationFiltersSchema = z.object({
  status: z.boolean().optional(),
  organization: z.string().optional(),
});

export type AmbassadorLeaderboardItem = z.infer<typeof ambassadorLeaderboardItemSchema>;
export type AmbassadorActivity = z.infer<typeof ambassadorActivitySchema>;
export type TravelGrantApplication = z.infer<typeof travelGrantApplicationSchema>;
export type TravelGrantStats = z.infer<typeof travelGrantStatsSchema>;
export type TravelGrantQualification = z.infer<typeof travelGrantQualificationSchema>;
export type ParticipantStatsData = z.infer<typeof participantStatsSchema>;
export type TravelGrantApplicationFilters = z.infer<typeof travelGrantApplicationFiltersSchema>;

