// List of Student Branches and Chapters
export const ORGANIZATIONS = [
  { value: 'enis', label: 'National Engineering School of Sfax' },
  { value: 'ensi', label: 'National School of Computer Science ENSI' },
  { value: 'supcom', label: 'Higher School of Communication of Tunis (Sup\'Com)' },
  { value: 'polytech-sousse', label: 'Ecole Polytechnique de Sousse' },
  { value: 'epp-monastir', label: 'Private Polytechnic School-Monastir' },
  { value: 'isi', label: 'Higher Institute of Computer Science' },
  { value: 'iset-rades', label: 'Higher Institute of Technological Studies of Rades' },
  { value: 'inat', label: 'National Agronomic Institute of Tunisia' },
  { value: 'iit', label: 'International Institute of Technology' },
  { value: 'polytech-sfax', label: 'Polytech Sfax' },
  { value: 'essths', label: 'Higher School of Sciences & Tech of Hammam Sousse' },
  { value: 'isims', label: 'Higher Inst of Informatics & Multimedia of Sfax' },
  { value: 'issat-mateur', label: 'Higher Inst of Applied & Tech Sciences of Mateur' },
  { value: 'eniso', label: 'National Engineering School of Sousse (ENISo)' },
  { value: 'ims', label: 'International Multidisciplinary School' },
  { value: 'isimm', label: 'Higher Inst Informatics & Mathematics of Monastir' },
  { value: 'enic', label: 'National Engineering School of Carthage' },
  { value: 'enig', label: 'National Engineering School of Gabes' },
  { value: 'insat', label: 'National Institute of Applied Sciences & Technology' },
  { value: 'fst', label: 'Faculty of Science of Tunis' },
  { value: 'enib', label: 'National Engineering School of Bizerte' },
  { value: 'ensit', label: 'Higher National Engineering School of Tunis' },
  { value: 'enim', label: 'National Engineering School of Monastir' },
  { value: 'fsb', label: 'Faculty of Sciences of Bizerte' },
  { value: 'enet', label: 'National School of Electronics & Telecoms of Sfax' },
  { value: 'isetcom', label: 'Higher Institute of Technological Studies ISET\'COM' },
  { value: 'upt', label: 'Private University of Tunis' },
  { value: 'issat-sousse', label: 'Higher Inst of Applied Science & Tech of Sousse' },
  { value: 'enstab', label: 'Natl School of Advanced Sci & Tech of Borj Cedria' },
  { value: 'enit', label: 'Ecole Nationale D\'Ingenieurs De Tunis' },
  { value: 'iset-djerba', label: 'Higher Institute of Technological Studies-Djerba' },
  { value: 'tekup', label: 'TEK-UP Higher School of Technologies & Engineering' },
  { value: 'sesame', label: 'SESAME University' },
  { value: 'isi-mahdia', label: 'Higher Institute of Informatics Mahdia' },
  { value: 'tps', label: 'Tunisia Polytechnic School' },
  { value: 'isimg', label: 'Higher Inst. of Computer Science Multimedia Gabes' },
  { value: 'central', label: 'Central University' },
  { value: 'isitc', label: 'Higher Inst of Information Technologies & Comm.' },
  { value: 'ismt', label: 'Higher Institute of Medical Tech of Tunis' },
  { value: 'espin', label: 'ESPIN University' },
  { value: 'ema', label: 'Manouba School of Engineering' },
  { value: 'fsg', label: 'Faculty of Sciences of Gabes' },
  { value: 'iset-nabeul', label: 'Higher Inst of Technological Studies of Nabeul' },
  { value: 'iset-kef', label: 'Higher Institute of Technological Studies of Kef' },
  { value: 'esprit', label: 'ESPRIT' },
  { value: 'esiet', label: 'Private Higher School of Eng. & Applied Tech' },
  { value: 'iset-bizerte', label: 'Institute of Technological Studies of Bizerte' },
  { value: 'iset-kairouan', label: 'Higher Institute of Tech. Studies of Kairouan' },
  { value: 'smu', label: 'South Mediterranean University' },
  { value: 'isigs', label: 'Higher Institute of Industrial Management of Sfax' },
  { value: 'fss', label: 'Faculty of Sciences of Sfax' },
] as const;

export type OrganizationValue = typeof ORGANIZATIONS[number]['value'];
